# .streamlit/secrets.toml

OPENAI_API_KEY = "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"

[connections.snowpark]
user = "RAVAGGA"
password = "Tr!cky123"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "AG84583.UK-SOUTH.AZURE"
